/** Buyer accounts used only for reviews/orders — realistic gamertags. */
export const BUYER_POOL = [
  { username: "JaylenK", email: "jaylen.kowalski@gmail.com" },
  { username: "MiraSol", email: "mira.solano@outlook.com" },
  { username: "TrevorNite", email: "trevornite@gmail.com" },
  { username: "KaiWaves", email: "kai.waves@icloud.com" },
  { username: "NinaLoot", email: "nina.loot@gmail.com" },
  { username: "OmarPixel", email: "omar.pixel@outlook.com" },
  { username: "CleoRanks", email: "cleo.ranks@gmail.com" },
  { username: "DylanF2P", email: "dylan.f2p@gmail.com" },
  { username: "IvyTrade", email: "ivy.trade@outlook.com" },
  { username: "RexValor", email: "rex.valor@gmail.com" },
  { username: "SashaGP", email: "sasha.gp@icloud.com" },
  { username: "LeoCraft", email: "leocraft@gmail.com" },
  { username: "ZaraBoost", email: "zara.boost@outlook.com" },
  { username: "FinnOSRS", email: "finn.osrs@gmail.com" },
  { username: "LunaSkins", email: "luna.skins@gmail.com" },
  { username: "ColeMyth", email: "cole.myth@outlook.com" },
  { username: "AriaGold", email: "aria.gold@gmail.com" },
  { username: "NoahQueue", email: "noah.queue@icloud.com" },
  { username: "EmmaR6", email: "emma.r6@gmail.com" },
  { username: "JakePoE", email: "jake.poe@outlook.com" },
  { username: "MayaFort", email: "maya.fort@gmail.com" },
  { username: "EliTarkov", email: "eli.tarkov@gmail.com" },
  { username: "RubyLoL", email: "ruby.lol@outlook.com" },
  { username: "SamGenshin", email: "sam.genshin@gmail.com" },
  { username: "HugoEVE", email: "hugo.eve@icloud.com" },
  { username: "ChloeCS", email: "chloe.cs@gmail.com" },
  { username: "BenWoW", email: "ben.wow@outlook.com" },
  { username: "LilyDota", email: "lily.dota@gmail.com" },
  { username: "MaxRL", email: "max.rl@gmail.com" },
  { username: "GraceFFXIV", email: "grace.ffxiv@outlook.com" },
  { username: "TylerApex", email: "tyler.apex@gmail.com" },
  { username: "HannahCoC", email: "hannah.coc@icloud.com" },
  { username: "ChrisGTA", email: "chris.gta@gmail.com" },
  { username: "OliviaWar", email: "olivia.war@gmail.com" },
  { username: "RyanMC", email: "ryan.mc@outlook.com" },
  { username: "SophieARK", email: "sophie.ark@gmail.com" },
  { username: "AlexPGo", email: "alex.pgo@icloud.com" },
  { username: "JordanBrawl", email: "jordan.brawl@gmail.com" },
  { username: "TaylorCR", email: "taylor.cr@outlook.com" },
  { username: "MorganNW", email: "morgan.nw@gmail.com" },
  { username: "CaseyAlb", email: "casey.alb@gmail.com" },
  { username: "RileyD4", email: "riley.d4@outlook.com" },
  { username: "QuinnDest", email: "quinn.dest@gmail.com" },
  { username: "AveryLost", email: "avery.lost@icloud.com" },
  { username: "ParkerWF", email: "parker.wf@gmail.com" },
  { username: "SkylarRblx", email: "skylar.rblx@outlook.com" },
  { username: "DrewCoD", email: "drew.cod@gmail.com" },
  { username: "BlakePoE2", email: "blake.poe2@gmail.com" },
  { username: "CameronSiege", email: "cameron.siege@outlook.com" },
  { username: "ReeseDiablo", email: "reese.diablo@gmail.com" },
  { username: "LoganAlb", email: "logan.alb@icloud.com" },
  { username: "PeytonBoost", email: "peyton.boost@gmail.com" },
  { username: "RowanTrade", email: "rowan.trade@outlook.com" },
  { username: "SageMarket", email: "sage.market@gmail.com" },
  { username: "PhoenixBuy", email: "phoenix.buy@gmail.com" },
  { username: "AtlasGold", email: "atlas.gold@outlook.com" },
  { username: "NovaCart", email: "nova.cart@icloud.com" },
  { username: "OrionDeal", email: "orion.deal@gmail.com" },
  { username: "VegaLoot", email: "vega.loot@outlook.com" },
  { username: "StormHex", email: "storm.hex@gmail.com" },
  { username: "EchoRank", email: "echo.rank@icloud.com" },
  { username: "FluxGear", email: "flux.gear@gmail.com" },
  { username: "NyxPrime", email: "nyx.prime@outlook.com" },
  { username: "ZenCart", email: "zen.cart@gmail.com" },
  { username: "BlitzGP", email: "blitz.gp@gmail.com" },
  { username: "CipherX", email: "cipher.x@outlook.com" },
  { username: "DriftMain", email: "drift.main@gmail.com" },
  { username: "GlitchOG", email: "glitch.og@icloud.com" },
  { username: "HavocRS", email: "havoc.rs@gmail.com" },
  { username: "IonStack", email: "ion.stack@outlook.com" },
  { username: "Jinxed", email: "jinxed.trades@gmail.com" },
  { username: "KiloWatt", email: "kilo.watt@gmail.com" },
  { username: "LynxBay", email: "lynx.bay@outlook.com" },
  { username: "MakoFury", email: "mako.fury@gmail.com" },
  { username: "NebulaOG", email: "nebula.og@icloud.com" },
  { username: "OnyxAce", email: "onyx.ace@gmail.com" },
  { username: "PulseKid", email: "pulse.kid@outlook.com" },
  { username: "QuartzOG", email: "quartz.og@gmail.com" },
  { username: "RiftKing", email: "rift.king@gmail.com" },
  { username: "SlateRun", email: "slate.run@outlook.com" },
  { username: "TitanOG", email: "titan.og@gmail.com" },
  { username: "UmberGP", email: "umber.gp@icloud.com" },
  { username: "VoltMain", email: "volt.main@gmail.com" },
  { username: "WispOG", email: "wisp.og@outlook.com" },
  { username: "XenLoot", email: "xen.loot@gmail.com" },
  { username: "YukiTrade", email: "yuki.trade@gmail.com" },
  { username: "ZedRank", email: "zed.rank@outlook.com" },
];

export const REVIEW_TEMPLATES: { rating: number; comment: string; gameHint?: string }[] = [
  { rating: 5, comment: "Insanely fast — seller was online within minutes and walked me through the whole trade step by step." },
  { rating: 5, comment: "Exactly as described. Delivery matched the listing time and the seller stayed in chat until I confirmed." },
  { rating: 5, comment: "Third order from this seller. Always reliable, always fair prices. Will buy again." },
  { rating: 5, comment: "Great communication throughout. Made the account transfer smooth even though I was nervous." },
  { rating: 5, comment: "Surprised how quick it was. Gold showed up at GE faster than I expected for the price." },
  { rating: 5, comment: "Professional seller. Sent progress screenshots during the boost and finished ahead of schedule." },
  { rating: 5, comment: "Honest and straightforward. No hidden steps, no pressure — just a clean trade." },
  { rating: 4, comment: "Took a little longer than the listing said but seller kept me updated the whole time. Still happy." },
  { rating: 5, comment: "Account matched the screenshots. Email change went through first try. Solid experience." },
  { rating: 5, comment: "Best rate I found after comparing a few offers. Delivery was under an hour." },
  { rating: 4, comment: "Good seller overall. Small delay waiting for EU morning hours but worth the wait." },
  { rating: 5, comment: "Boost team was legit — Diamond player duo'd with me and we climbed two divisions in a night." },
  { rating: 5, comment: "Item trade was quick at the hideout. Would recommend for PoE currency." },
  { rating: 5, comment: "Seller answered every question before I paid. Felt safe the entire time." },
  { rating: 4, comment: "Solid trade. Instructions were clear. Only wish delivery was 10 minutes faster." },
  { rating: 5, comment: "OG skins account was legit. Full email access on delivery like promised." },
  { rating: 5, comment: "Repeat customer — never had a problem across gold, items, and one account purchase." },
  { rating: 5, comment: "Met at Grand Exchange, trade went smooth. 50M GP for a fair price." },
  { rating: 4, comment: "Good experience. Seller was polite and patient while I figured out the trade window." },
  { rating: 5, comment: "WoW gold delivered via mail within the hour. Realm and faction exactly as requested." },
  { rating: 5, comment: "Valorant boost finished over the weekend. VPN used, no issues on my account." },
  { rating: 5, comment: "Fast and swift. No issues, straight in and out. Highly recommend." },
  { rating: 5, comment: "Custom order delivered nicely, good rates too. Thank you!" },
  { rating: 4, comment: "Everything fine. Seller helped remove the linked Google account on my new main." },
  { rating: 5, comment: "Quick and fast delivery. Definitely buying again next league." },
  { rating: 5, comment: "Very helpful seller, responds instantly and always here to help." },
  { rating: 5, comment: "Gotta admit I was skeptical at first but seller delivered exactly what was listed." },
  { rating: 4, comment: "Decent price, decent speed. Communication could be a touch faster but trade was fine." },
  { rating: 5, comment: "100k gold kept me going for the week. Good price, fast seller." },
  { rating: 5, comment: "Verified seller badge earned — transaction felt as safe as the site promises." },
  { rating: 5, comment: "Fortnite account had every skin listed. Login details worked immediately." },
  { rating: 4, comment: "Tarkov roubles trade took two raids but seller knew the safest route." },
  { rating: 5, comment: "Genshin account had all the characters advertised. Asia server transfer was smooth." },
  { rating: 5, comment: "EVE contract arrived in Jita within 20 minutes. Will use for bulk ISK again." },
  { rating: 5, comment: "LoL smurf was level 30 with BE ready. Ranked placements same day." },
  { rating: 4, comment: "Minor typo in instructions but seller clarified in under a minute." },
  { rating: 5, comment: "Mythic+ carry team knew every route. Vault filled, zero drama." },
  { rating: 5, comment: "Robux via game pass method worked. Seller explained the 48h friend wait upfront." },
  { rating: 5, comment: "CS2 skins trade was quick and prices beat steam market for what I needed." },
  { rating: 4, comment: "Lost Ark gold took about 90 minutes but seller warned me about server maintenance first." },
  { rating: 5, comment: "FFXIV gil trade on Crystal — smooth face-to-face, no market tax hassle." },
  { rating: 5, comment: "Diablo 4 items matched the tier listed. Hideout trade, instant invite." },
  { rating: 5, comment: "OSRS fire cape service done overnight. Hand-played, no bots." },
  { rating: 4, comment: "Good seller. Apex coins via gift took a day but that's on EA not the seller." },
  { rating: 5, comment: "Clash account transfer through Supercell ID was guided perfectly." },
  { rating: 5, comment: "Warframe plat gift arrived after MR check. Patient seller." },
  { rating: 5, comment: "Pokemon Go account — seller helped unlink the old Google login. Stress-free." },
  { rating: 4, comment: "Brawl stars account as described. Would've liked more screenshots upfront but all good." },
  { rating: 5, comment: "New World gold via trade post. Fair rate compared to other offers I browsed." },
];
